# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genero',
            field=models.CharField(choices=[('UX', 'UX'), ('CM', 'Comedia'), ('TR', 'Terror'), ('DR', 'Drama'), ('CN', 'Ciencia'), ('CU', 'Cuento'), ('EN', 'Ensayo'), ('PR', 'Programación')], max_length=20),
        ),
    ]
